import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../../services/api.js';
import { MapPin, Navigation } from 'lucide-react';

export default function RouteMap() {
  const mapNode = useRef(null), map = useRef(null);
  const [orders, setOrders] = useState([]); const [area, setArea] = useState('your ward');
  useEffect(() => { api.get('/officer/complaints').then(res => { setOrders(res.data.complaints || []); setArea(res.data.officerInfo?.area || 'your ward'); }).catch(() => {}); }, []);
  useEffect(() => { let alive = true; if (!mapNode.current || !orders.length) return; import('leaflet').then(L => { if (!alive || map.current) return; const points = orders.filter(o => o.latitude && o.longitude); if (!points.length) return; const instance = L.default.map(mapNode.current).setView([points[0].latitude, points[0].longitude], 14); L.default.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '© OpenStreetMap' }).addTo(instance); const bounds = []; points.forEach((o, index) => { const color = o.priority === 'P1' ? '#DC2626' : o.priority === 'P2' ? '#D97706' : '#00B4D8'; const icon = L.default.divIcon({ className: '', html: `<div style="width:28px;height:28px;border-radius:50%;background:${color};color:white;border:3px solid white;display:flex;align-items:center;justify-content:center;font-weight:800;box-shadow:0 2px 6px #555">${index + 1}</div>` }); L.default.marker([o.latitude, o.longitude], { icon }).addTo(instance).bindPopup(`<b>${o.complaintId}</b><br/>${o.title}<br/><small>${o.address || ''}</small>`); bounds.push([o.latitude, o.longitude]); }); if (bounds.length > 1) instance.fitBounds(bounds, { padding: [35, 35] }); map.current = instance; }); return () => { alive = false; if (map.current) { map.current.remove(); map.current = null; } }; }, [orders]);
  return <div className="fade-in"><h1 className="page-title">Field Route Map</h1><p className="page-subtitle">Assigned work orders across {area}, arranged by priority for your field run.</p><div className="card" style={{ padding: 0, overflow: 'hidden' }}><div style={{ padding: '14px 18px', display: 'flex', gap: 8, alignItems: 'center', fontWeight: 700 }}><Navigation size={18} style={{ color: 'var(--teal-600)' }} />{orders.length} assigned stops</div><div ref={mapNode} style={{ height: 540, background: 'var(--gray-100)' }} />{!orders.length && <div className="empty-state"><MapPin size={34} /><div className="empty-state-title">No mapped work orders yet</div></div>}</div><div style={{ display: 'grid', gap: 10, marginTop: 18 }}>{orders.map((o, i) => <Link key={o._id} to={`/officer/complaints/${o.complaintId}`} className="card" style={{ padding: 13, textDecoration: 'none', color: 'var(--gray-800)', display: 'flex', gap: 10, alignItems: 'center' }}><span style={{ background: 'var(--primary-600)', color: 'white', width: 25, height: 25, borderRadius: '50%', display: 'grid', placeItems: 'center', fontWeight: 800 }}>{i + 1}</span><span><strong>{o.title}</strong><small style={{ display: 'block', color: 'var(--gray-500)' }}>{o.address || 'Location tagged'}</small></span></Link>)}</div></div>;
}
